### PR TITLE
TDR-3246 Log group Retention

### PR DESCRIPTION
**Pull request by thanhz**
Adds the `retention_in_days` variable for creating log groups

### CODE REVIEW

**Review by TomJKing — COMMENTED** [review]
Looks good. One comment. Will this not set all the cloudwatch groups to 0 days retention? We shouldn't be doing this, if it does.

**Comment by thanhz** [comment]
> Looks good. One comment. Will this not set all the cloudwatch groups to 0 days retention? We shouldn't be doing this, if it does.
Looking at the [terraform docs](https://registry.terraform.io/providers/hashicorp/aws/3.28.0/docs/resources/cloudwatch_log_group#retention_in_days) setting 0 day retention means that _"the events in the log group are always retained and never expire"_
I've already applied this on intg looks like this is the case.

**Comment by TomJKing** [comment]
Ahh, OK. Not all the existing cloudwatch log groups have never expire, so need to check all of these when running the new modules to ensure their current retention policy is not affected by this change.

**Review by TomJKing — APPROVED** [review]

**Comment by thanhz** [comment]
Looks good. The change doesn't modify any existing cloud logs. 
image

**Comment by TomJKing** [comment]
It'll probably impact the log groups created in the other terraform repos. Should catch that when the sub-module hashes are updated for those repos.

**Pull request merged**
